# CLASE 07 Creación de Arrays
## Prof. Andrés Mena Abarca
### Estudiantes: Fernanda Salas

### Crear un array a partir de una lista

In [1]:
import numpy as np



### Crear un array de ceros de tamaño 5x5

un Array es una estructura de filas y columnas.

In [ ]:
#Código crear un array de ceros de tamaño 5x5

array_ceros = np.zeros((5,5)) 
print(array_ceros)




[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [ ]:
#Código crear un array de unos de tamaño 3x3
array_unos = np.ones((2,3)) #primer valor es X y el segundo es Y, ones hace que todo sea en 1
print(array_unos)



[[1. 1. 1.]
 [1. 1. 1.]]


### Crear un array con valores espaciados uniformemente de 0 a 9

In [ ]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
array_linear = np.linspace(0,9,10) #hace un calculo lineal tiene un inicio, avanza hasta que llega a un limite
#0 es de donde salgo
#9 es hasta donde llego 
#10 es cuantos espacios avanzo
print(array_linear)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [6]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
array_reto = np.linspace(0, 1, 6)
print(array_reto)

[0.  0.2 0.4 0.6 0.8 1. ]


# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [ ]:
array_salario = np.array([50,40,20], [(2,4,3)])
array_propinas = np.array([6,4,9])
#va haciendo operaciones matematicas con el valor que está en el mismo 
#parámetro que el. 50 + 6, 40 + 4... si solo dejo tres, la segunda columna
#sumará con el de abajo 2+6, 4+4...
#el array es una lista

#Código realizar una suma, resta, multiplicación y división entre dos arrays

suma = array_salario + array_propinas
print(suma)

# Salida
'''
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)
'''

[56 44 29]


'\nprint("La suma es: ",suma)\nprint("La resta es: ",resta)\nprint("La multiplicacion es: ",multiplicacion)\nprint("La division es: ",division)\n'

In [ ]:
#Calcular el producto punto de dos arrays


In [ ]:
#Transponer un array


# Operaciones Estadísticas

In [ ]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media
media = np.mean(array_numeros)
print(f'la media es: {media}')
# Calcular la suma
suma = np.sum(array_numeros)
print(f'la suma es: {suma}')
# Calcular el valor mínimo
minimo = np.min(array_numeros)
print(f'la minima es: {minimo}')

# Calcular el valor máximo
maximo = np.max(array_numeros)
print(f'la maxima es: {maximo}')

'''
# Mostrar los resultados
print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)
'''
####################libreria numpy.org##############################

la media es: 3.0
la suma es: 15
la minima es: 1
la maxima es: 5


'\n# Mostrar los resultados\nprint("La media es:", media)\nprint("La suma es:", suma)\nprint("El valor mínimo es:", valor_minimo)\nprint("El valor máximo es:", valor_maximo)\n'

In [14]:
#Cambiar la forma de un array "reshape"

# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
array_reshapeado = array_original.reshape(2,3)
print(array_reshapeado)

'''
# Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)
'''

[[1 2 3]
 [4 5 6]]


'\n# Imprimir el array original y el reshapeado\nprint("Array original:", array_original)\nprint("Array reshapeado:", array_reshapeado)\n'

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [ ]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2

#print(determinante)

### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3


# Calcular la matriz inversa


# Imprimir la matriz inversa



### Calcular los valores propios y vectores propios de una matriz 4x4

In [ ]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

# Funciones Universales

In [ ]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de los ángulos

# Calcular el coseno de los ángulos

# Calcular la exponencial de los ángulos

# Calcular el logaritmo natural de los ángulos


In [ ]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Obtener la primera fila del array


# Obtener la última columna del array
  # [3, 6, 9]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]

# Imprimir los subconjuntos de datos extraídos


# Generación de Números Aleatorios

In [ ]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100


In [ ]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1


In [ ]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)



# ejercicios reales o prácticos

In [ ]:
#preferencia de películas Mariana[Accion, Comedia, Drama]
mariana = np.array([7,9,2])
#se categorizara del 1 al 10 en cuanto a accion, comedia, drama, en ese orden
Avatar = np.array([10,1,5]) #mas accion y menos comedia
Brave_heart = np.array([8,1,7]) #mas accion y menos comedia

#calcular la similitud de cada pelicula con los gustos de mariana
similitud_p1 = np.dot(mariana,Avatar) #multiplicara los puntos
similitud_p2 = np.dot(mariana, Brave_heart) 
print(f'similitud de preferencias Avatar: {similitud_p1}')
print(f'similitud de preferencias Brave Heart: {similitud_p2}')

#se puede hacer con un input, del 1 al 10 que tanto le gusta X pelicula, etc.
if similitud_p1 > similitud_p2:
    print('le recomendamos Avatar')
else:
    print('le recomendamos ver Brave Heart')



similitud de preferencias Avatar: 89
similitud de preferencias Brave Heart: 79


In [18]:
#segundo ejercicio correlacion
import numpy as np
#Datos Tipo Cambio Dolar Ultimos 10 meses | IPC , metrica mesual


tipo_cambio = np.array([506.96,505.00,504.27,505.52,506.23,506.23,506.23,506.58,506.87,507.25])
ipc = np.array([109.46,109.55,109.71,109.57,109.70,109.33,108.85, 109.36,110.39,110.79])


#Calcular coeficiente de correlación
correlacion =  np.corrcoef(tipo_cambio,ipc)[0,1]


print(f'Coeficiente de correlación: {correlacion:.2f}')


Coeficiente de correlación: 0.32


## Estudio de horas Vrs Notas

In [25]:
#Datos: horas de estudio y notas obtenidas
horas_estudio = np.array([1,2,3,4,5,6,7,8,9,10]) #horas de estudio
notas = np.array([50, 55, 60, 63, 67, 72, 75, 78, 81, 85]) #notas

#calculo del crecimiento del promedio del puntaje por hora de estudio
#1. calcular la diferencia entre los puntajes
diferencias_notas = np.diff(notas) #esto calcula la variacion entre una nota y la siguiente
print(diferencias_notas)

#calculo el promedio de la diferencia
incremento_notas = np.mean(diferencias_notas)
print(f'el incremento de promedio por cada hora de estudio: {incremento_notas:.2f}')

#estimacion del puntaje si estudio 12 horas
proyeccion_estudio = 12
nota_estimada = (proyeccion_estudio - max(horas_estudio)) * incremento_notas
print(nota_estimada) #subo 7.8 puntos por cada hora de estudio

#estimacion de nota estimada por hora de estudio
hora_estudiada = 6
nota_porhora = (proyeccion_estudio - max(horas_estudio)) * incremento_notas * max(notas)
nota_minima_estimada = (proyeccion_estudio - min(horas_estudio)) * incremento_notas * min(notas)

print(nota_porhora)
print(nota_minima_estimada)

[5 5 3 4 5 3 3 3 4]
el incremento de promedio por cada hora de estudio: 3.89
7.777777777777778
661.1111111111111
2138.888888888889
